#!/bin/bash

#  makemake.sh
#  XTBook
#
#  Created by Nexhawks on 4/19/11.
#  Copyright 2011 Nexhawks. All rights reserved.

if [ "$1" == "" ]; then
	echo "USAGE: makemake.sh SRCPATH"
	exit 1
fi

SRCPATH="$1"

if [ -e "$SRCPATH/main.cpp" ]; then
	echo "$SRCPATH/main.cpp confirmed." 
else
	echo "$SRCPATH/main.cpp not found!"
	exit 2
fi

OUTFILE="Makefile.i"
SRCFILES="$SRCPATH/*.cpp $SRCPATH/data/*.c $SRCPATH/tcw/*/*.cpp"
SRCFILES+=" $SRCPATH/TWiki/*.cpp $SRCPATH/OptimizedBranch/*.cpp $SRCPATH/TPList/*.cpp"
SRCFILES+=" $SRCPATH/TinyXML/*.cpp $SRCPATH/RichgelJpeg/*.cpp $SRCPATH/XZEmbedded/*.c"
PREFIXHEADER="XTBook_Prefix.pch"
PCPREFIXHEADER="XTBook_Prefix.pch.gch"
OBJS=""


echo "# Generated by makemake.sh" > "$OUTFILE"

echo "SRCPATH=${SRCPATH}" >> "$OUTFILE"

echo "${PREFIXHEADER}:		${SRCPATH}/${PREFIXHEADER}"  >> "$OUTFILE"
echo "	cp ${SRCPATH}/${PREFIXHEADER} ${PREFIXHEADER}"  >> "$OUTFILE"
echo "${PCPREFIXHEADER}:	${PREFIXHEADER}" >> "$OUTFILE"
echo "	\$(CXX) -x c++-header ${PREFIXHEADER} \$(CFLAGS) \$(CXXFLAGS) -o ${PCPREFIXHEADER} -I.." >> "$OUTFILE"

for FILE in $SRCFILES; do
	BASENAME=`basename "$FILE"`
	OBJ=${BASENAME/.cpp/.o}
	OBJ=${OBJ/.c/.o}

	echo "${OBJ}:	${FILE} ${PCPREFIXHEADER}" >> "$OUTFILE"
	if [[ $FILE == *.cpp ]]; then
		echo "	\$(CXX) -include ${PREFIXHEADER} -c ${FILE} -o ${OBJ} \$(CFLAGS) \$(CXXFLAGS) -I.." >> "$OUTFILE"
	else
		echo "	\$(CC) -c ${FILE} -o ${OBJ} \$(CFLAGS)" >> "$OUTFILE"
	fi
	
	OBJS+=" $OBJ"
done

echo "OBJS=${OBJS}" >> "$OUTFILE"
echo "PCPREFIXHEADER=${PCPREFIXHEADER}" >> "$OUTFILE"




